name: Notify Discord on Push

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification to Discord
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"username": "GitHub Bot", "content": "🚀 **${{ github.actor }}** just pushed new changes!\n🔗 [View Commit](https://github.com/${{ github.repository }}/commit/${{ github.sha }})"}' \
               ${{ secrets.DISCORD_WEBHOOK }}
